### ISSUE TITLE
$result 변수가 중복으로 사용되고 있습니다.

### ISSUE THREAD

**Issue by angelbro** [gnuboard/gnuboard5#100]
https://github.com/gnuboard/gnuboard5/blob/6090b0de1822a94bd14b56fd6b407fd8664b3710/adm/index.php#L46

$result 변수가 중복으로 사용됩니다.
이럴 경우 "신규가입회원", "최근게시물", "최근포인트발생내역" 섹션의 위치를 변경할 때 쿼리를 제대로 가져올 수 없는 경우가 발생합니다.

**Comment by devrainbow** [comment]
그누보드가 그렇지 뭐... 라이믹스 쓰세요

**Comment by kagla** [comment]
@angelbro 답변이 늦었습니다. 
섹션의 위치라는 것이 정확하게 어떤 것을 말씀하시는 것인가요?
