### ISSUE TITLE
1:1 문의 파일 첨부 오류, 작은별님 문의

### ISSUE THREAD

**Issue by gnuboard** [gnuboard/gnuboard5#101]
https://sir.kr/cm_bug/11500

===============================================

https://sir.kr/qa/431931
 

QA 하다가 발견한 건데요.
 

1:1 문의 게시판에 신규 글 등록 시 파일 첨부는 지원합니다.

근데 답변 모드일 때는 파일 첨부가 기본적으로 나타나지 않죠.

그런데 답변 등록 후 답변을 수정하면 또 파일 첨부란이 뜨고 있네요.

답변 수정 모드일 때 첨부하면 파일은 등록되지만 출력되는 곳도 없고요.

**Comment by projectSylas** [comment]
QA : php8버전 관련 이슈 수정 f305701e6193eea93b400530850baaf105d1fe81 완료
