### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [gnuboard/gnuboard5#130]
Hey there!

I belong to an open source security research community, and a member (@wjddnjs33) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by gnuboard** [comment]
Hello.
We received an email from the memeber(@wjddnjs33) and patched it as follows.
thank you.

// Fix an error that allow you can specify another domain in the url (Pocas, 211208)
https://github.com/gnuboard/gnuboard5/commit/d28c165fdfe08a98313fbbea02f770ed7dcf1800

// [Security Patch] (KVE-2021-1846) Fix check_url_host function bypass vulnerability when sending by inserting the line feed "%0A" value into the url value (Pocas)
https://github.com/gnuboard/gnuboard5/commit/d87802eb946e378a9810385acf27f3a8859cc282


안녕하세요.
우리는 그 분(@wjddnjs33)에게 메일을 받고 아래와 같이 패치를 하였습니다.
감사합니다.

// url에 타도메인을 지정할 수 있는 오류 수정 (Pocas님,211208)
https://github.com/gnuboard/gnuboard5/commit/d28c165fdfe08a98313fbbea02f770ed7dcf1800

// [보안패치] (KVE-2021-1846) url 값에 Line feed인 "%0A" 값을 삽입하여 전송하는 경우 check_url_host 함수 우회 취약점 수정 (Pocas님)
https://github.com/gnuboard/gnuboard5/commit/d87802eb946e378a9810385acf27f3a8859cc282

**Comment by JamieSlome** [comment]
@gnuboard - just a heads up that we received a report from another user @9o3.

You can view it directly here:
https://huntr.dev/bounties/c8c2c3e1-67d0-4a11-a4d4-11af567a9ebb/
