### ISSUE TITLE
그누보드의 php 최저버전 기준 올리지는 않나요?

### ISSUE THREAD

**Issue by happy-korea** [gnuboard/gnuboard5#153]
지금 최저지원 버전이php 5.2 기준인데

언제까지 구버전을 가지고 갈껀가요? 계획은 있는지요
cms가 계속 지원하니까 아직도 php 5.2버전으로 신규플젝하는곳 있고요

최소 5.3~5,4으로 올려야하는건 아닌지요

그누 6가 나오면 7.0이상이라던지...

**Comment by jakekwak** [comment]
그누보드의 장점이자 단점이겠죠.  PHP버전이 올라간다는 것은 그만큼 새로운 PHP기능을 썼다는 것인데,  낮은 버전에서도 동작한다면 기본적인 함수만 사용해서 만들었다는 것이죠.

상위버전은 하위 호환되니..  최근에 PHP 8지원을 위해서 변경된 부분도 있는데,  이 부분이 하위버전에서 문제가 생긴다면 버전업을 하겠죠.

**Comment by kagla** [comment]
안녕하세요.
수정된 코드로 인하여 운영이 중단되는 일은 없어야 하므로 이점 충분히 고려하여 패치하겠습니다.
감사합니다.
