### ISSUE TITLE
data 폴더 추가

### ISSUE THREAD

**Issue by jakekwak** [gnuboard/gnuboard5#154]
데이타 폴더에 .gitignore 파일 넣고
```
data
  - .gitignore 
```

내용을 아래와 같이 하면 data폴더가 남아 있을 것 같습니다.

```
*
!.gitignore
```

git clone후에 mkdir 안해도 되서 한 스텝 줄일 수가 있죠.

git clone시 폴더에 속성(707)을 넣는 방법은 검색을 해도 안나오네요

**Comment by kagla** [comment]
안녕하세요.
좋은 내용 감사힙니다.
설치 안내 페이지 등을 수정해야 하는 관계로 현재 배포되는 버전에서는 적용하지 않는 것으로 하겠습니다.
감사합니다.
