### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by 9o3** [gnuboard/gnuboard5#157]
Hi there, I have been trying to get in touch with you regarding a security issue. 

More information can be found here: #130 
I assumed you missed the communication & comment on the closed issue, which is why I'm making a new issue for visibility :) 

Thank you for your consideration :)

**Comment by kagla** [comment]
I'm so sorry.
I've been very busy lately, so I'm late to check the issue.
I checked the "bbs/current_connect.php" code you gave me, but I couldn't get an e-mail address.
For example, I couldn't find the code you gave me on "https://sir.kr/bbs/current_connect.php".
Please let me know where I can get codes such as "formmail.php" or "email".
Thank you.

**Comment by 9o3** [comment]
Hi Kagla,

I have updated the huntr.dev report with steps on how to re-produce this. Please see https://huntr.dev/bounties/c8c2c3e1-67d0-4a11-a4d4-11af567a9ebb/ for further information.

**Comment by JamieSlome** [comment]
@kagla - seeing as we haven't received a response on our report, and more than 90 days have elapsed since the date of disclosure, we wanted to provide 4 days fair warning before making the report public, on request from the researcher.

Please respond in the meantime, if you need more time 👍
