### ISSUE TITLE
이미지 파일명을 통한 아이피 노출 문제

### ISSUE THREAD

**Issue by kjsman** [gnuboard/gnuboard5#172]
안녕하세요,

[버전 5.5.3.1의 bbs/write_update.php](https://github.com/gnuboard/gnuboard5/blob/v5.5.3.1/bbs/write_update.php#L570)에서,

```php
$upload[$i]['file'] = abs(ip2long($_SERVER['REMOTE_ADDR'])).'_'.substr($shuffle,0,8).'_'.replace_filename($filename);
```

이와 같이 업로드된 파일의 파일명을 지정하고 있습니다. 여기에서 `abs(ip2long($_SERVER['REMOTE_ADDR']))`을 파일명에 포함시키고 있는데, 이는 '접속자의 아이피를 정수형으로 전환한 것'을 의미합니다.

글에 접근할 수 있는 모든 사용자는 파일명을 확인할 수 있습니다. 즉, 이미지를 포함한 글을 올린 사람의 아이피 주소가 파일명을 통해 다른 사용자에게 노출됩니다.

이를 해결하기 위해서는, 파일명이 글쓴이의 아이피 주소를 포함하지 않도록 수정해야 합니다.

**Comment by kagla** [comment]
안녕하세요. 
여러가지 테스트를 하느라 답변이 늦었습니다.

아주 오래전에 작성된 코드라 정확하게 기억나지는 않지만 파일을 다량으로 업로드 하는 사용자를 찾아 IP 차단등의 용도로 사용하기 위해 ip2long 함수를 썼던 것으로 알고 있습니다.

나중에 이 파일을 누가 올렸는지 파악해야 한다면 어떤 코드로 대체해야 하는게 좋을까요?

**Comment by RachelleVanmeter** [comment]
파일명에다가 기록하는게 아닌 DB에 기록하는건 어떠하신가요?

**Comment by kagla** [comment]
> 

테이블에 필드를 추가하는건 절제하고 ip2long 을 md5 나 sha1 으로 사용하는 것으로 생각하고 있습니다.

**Comment by kjsman** [comment]
IP를 단순 해시 처리하게 되면 [브루트포싱](https://security.stackexchange.com/a/64606)으로 해당 IP 주소를 찾을 수 있을 것이라 생각됩니다. 혹시 다른 방법은 없을까요?

**Comment by kagla** [comment]
ip2long 관련 코드는 md5(sha1(IP)) 로 모두 변경될 예정입니다. 감사합니다.
