### ISSUE TITLE
is_admin 의 run_replace가 동작하지 않음.

### ISSUE THREAD

**Issue by djacks6278** [gnuboard/gnuboard5#173]
common.php 내의 is_admin 함수에 대해서 run_replace가 정상 동작하지 않습니다.

common.php 파일내의 run_event('common_header'); 훅이나 extend 호출이 is_admin을 선언한 후 이루어지기 때문에
is_admin 함수에 대한 훅이 동작하지 않습니다.

이를해결하기 위해서

extend 호출의 위치 조정이 필요할듯 합니다.

**Comment by djacks6278** [comment]
수정합니다.
extend 호출 위치 조정만으로는 추후 다른 extend 활용에 문제가 생길듯 싶습니다.
때문에 커뮤니티 내 만수킴 님의 팁(https://sir.kr/g5_tip/13915?sfl=wr_name%2C1&stx=%EB%A7%8C%EC%88%98%ED%82%B4)
을 바탕으로 하여 최신버전에 맞춰 extend 내 pre 폴더를 따로 마련하여
이를 선 로드하는 방식의 코드 수정이 필요해 보입니다.

임의로 코드를 작성해보았습니다.

327라인
```
//==============================================================================
// 공용 변수
//------------------------------------------------------------------------------
// 기본환경설정
// 기본적으로 사용하는 필드만 얻은 후 상황에 따라 필드를 추가로 얻음
$config = get_config(true);
```

을 아래와 같이 변경하여 pre extend와 hook 두가지를 추가했습니다.

```
// common.php 파일을 수정할 필요가 없도록 확장합니다.
// common 의 run_replace 위한 extend 폴더내 pre 폴더 파일 먼저 로드
// config 를 불러오기 전이므로 경로 직접 지정
$pre_extend_file = array();
$pre_tmp = dir('extend/pre');
while ($entry = $pre_tmp->read()) {
    // php 파일만 include 함
    if (preg_match("/(\.php)$/i", $entry))
        $pre_extend_file[] = $entry;
}

if(!empty($pre_extend_file) && is_array($pre_extend_file)) {
    natsort($pre_extend_file);

    foreach($pre_extend_file as $file) {
        include_once('extend/pre/'.$file);
    }
    unset($file);
}
unset($pre_extend_file);

// config 로드전 훅 추가
run_event('common_config_before');

//==============================================================================
// 공용 변수
//------------------------------------------------------------------------------
// 기본환경설정
// 기본적으로 사용하는 필드만 얻은 후 상황에 따라 필드를 추가로 얻음
$config = get_config(true);

// config 로드후 훅 추가
run_event('common_config_after');
```

이로써 extend내 pre 라는 폴더를 추가로 기본적으로 마련하고,
해당 폴더 내 php를 각종 lib 과 db연결이 완료되고 세션이 시작된 시점에서 로드하고

config파일을 로드하기전 , 후 각종 변수 활용의 차이를 염두에 두어
두가지 훅을 추가함으로써 조금더 확장된 접근이 가능할듯 합니다.

get_config 의 run_replace 등과 같이 추가적인 common.lib 내의 run_replace 들이 동작하게 됩니다.

**Comment by kagla** [comment]
안녕하세요.

이미 많은 사용자님들께서 사용하고 계시리라 생각되며, 구조를 변경하는 것은 어렵다고 판단됩니다.

이와 같은 방식으로 사용하시는 것은 어떨런지요?

extend/_user.hook.php

```
<?php
include_once("_common.php");

add_replace('is_admin', 'test_is_admin', 5, 2);

function test_is_admin($is_authority, $mb_id) 
{
  $is_authority = "ulalalala";
  return $is_authority;
}
?>
```

test.php

```
<?php
include_once("_common.php");

echo is_admin($member['mb_id']);
?>
```




common.php 에 보시면

if(!empty($extend_file) && is_array($extend_file)) {
    natsort($extend_file);

와 같이 

natsort() 를 사용하고 있습니다.

그러므로 _ (underline) 를 파일의 앞에 붙이신다면 비슷한 효과를 얻을 수 있으리라 생각됩니다.


요청하신 방법으로 처리하지 못함을 양해해 주십시오.

감사합니다.

**Comment by djacks6278** [comment]
제시해주신 방향으로는 사용하기 불가합니다...
어떤 이유로 추가가 불가한지 궁금합니다.

또한 제시해준 방법은 기존 extend와 별반 다를바가 없고 제가 제시한 방법과 연관성이 보이지 않습니다.

제가 말씀드리는 is_admin은 일반적인 함수 호출이 아닌
common.php 호출시 $is_admin 변수의 설정에 지정된 is_admin 함수를 말하는것입니다.
제시해주신 방법으로 변경후 시도해보아도 기존처럼 반응하지 않습니다.

포괄적인 문제를 떠나서 $is_admin을 재선언 한다고 하더라도, 이미 접속 차단등의 절차가 진행된 후 이기때문에

예시기능으로 관리자를 추가한다고 했을때,

1. 추가된 관리자가 접속을 시도
2. 만약 사이트가 접속을 차단중이라면 (허용,차단 IP 등)
3. $is_admin 재설정을 위해 extend를 호출할 수 없고 그대로 사이트는 die 를 리턴

이 문제로 인해 활용을 위해서는 다른 해결법이 필요해보입니다..
