### ISSUE TITLE
SMTP설정 분리에 관한 질문 드립니다.

### ISSUE THREAD

**Issue by RachelleVanmeter** [gnuboard/gnuboard5#176]
제 개인 서버에서 4시간마다 master 브런치의 새로운 코드를 받도록 crontab설정을 해두었으며
매번 잘 업데이트가 되다 최근 config.php 파일이 업데이트가 되면서 제가 SMTP를 다른걸로 변경을 해두었는데
충돌로 업데이트가 진행이 되지 않습니다.

기본 SMTP는 localhost로 되어 있는걸로 아는데 제 서버에서는 해당 주소를 사용할시 메일 전송이 않되어 변경했습니다.
SMTP설정을 config.php에서 분리요청을 검토 부탁드립니다.

감사합니다.

**Comment by kagla** [comment]
redefine 으로 사용해 보시기 바랍니다.

https://www.google.com/search?q=php+redefine&oq=php+redifine&aqs=chrome.1.69i57j0i13l2j0i13i30l2j0i10i30j0i13i30j0i10i13i30l2j0i13i30.6239j0j7&sourceid=chrome&ie=UTF-8
