### ISSUE TITLE
이슈 #131 에 대한 추가 패치

### ISSUE THREAD

**Issue by mdsnins** [gnuboard/gnuboard5#186]
해당 #131 이슈로 인한 패치가 완벽하게 적용되지 않았습니다.

https://github.com/gnuboard/gnuboard5/commit/84a065c31b264611897d577338340dd87fb68ef6 의 host check 하는 커밋 부분은

```php
        // host 가 inicis.com 의 주소가 아니라면 false 반환
        // [scheme] => https, [host] => fcstdpay.inicis.com, [path] => /api/payAuth
        if (preg_match("#inicis\.com$#", $url_data["host"]) == false) {
            // error_log(print_r($url_data, 1));
            return false;
        }
```

로, 정규표현식 `inicis\.com$` 과 매치되는지 확인합니다.
이는 `lovediveinicis.com` 와 같이, 실제로 `inicis.com`의 호스트가 아닌 경우에도 preg_match를 통과하게 합니다.

preg_match에 대응되는 정규표현식 패턴을 수정할 필요가 있습니다.

감사합니다.

**Comment by KimTom89** [comment]
말씀하신 내용을 토대로 `.inicis.com` 호스트로 매칭될 수 있도록 정규표현식을 수정했습니다.
해당 내용은 5.5.8 버전에도 반영되었습니다.
알려주셔서 감사합니다 :)

host check 참고 (이니시스 PC(웹표준)결제 > 방화벽 정보)
![image](https://user-images.githubusercontent.com/57935683/173303981-e38cee5e-e4c5-4021-8dce-e53a7310e8de.png)
