### ISSUE TITLE
세션데이터 파일을 직접 다운로드 할수 있는 보안문제

### ISSUE THREAD

**Issue by jihan001** [gnuboard/gnuboard5#189]
#175 이슈에서 알수있는 것처럼 일반 방문자가 `data/session` 디렉토리에 있는 세션 대이터 파일을 다운로드 할수있음.

그누보드의 세션에 소셜로그인 서비스들의 API 설정의 주요 데이터가 담겨있는 상황에서 해당 데이터를 제외하여 해결할수있으나 서드파티에서 세션에 중요 데이터를 담겨질 상황도 고려해야함.

이미 그누보드에서 기본 제공하는 소셜 로그인 기능의 설정에 입력한 소셜 로그인 서비스의 API 시크릿 키가 누출되고있는 상황입니다.

세션 데이터 파일에 직접 엑세스하여 다운로드할수 없도록 차단하는 조치가 필요합니다.

개별사용자가 설정할 수 있겠으나 그누보드가 기본 제공/생성하는 .htaccess 파일 등에 세션 데이터를 차단하는 룰을 추가하여 방지해야합니다.

**Comment by YJSoft** [comment]
https://github.com/gnuboard/gnuboard5/blob/ecd2b1c72abd02ac296435855a41c1de346e2ade/common.php#L211

임시조치로 위 한줄을 삭제하면 세션 저장경로가 웹에서 접근 불가능한 기본 경로로 되돌아갑니다. 세션 저장 경로는 변경해야 할 이유가 전혀 없으며 불필요한 변경은 위와 같은 보안이슈의 원인이 됩니다.

**Comment by jihan001** [comment]
https://sir.kr/cm_free/756649

세상에 10년 전에 이미 문제를 알고 있었는데도 중간에 농담 따먹기하다가 그냥 방치됐군요. 😱

**Comment by thisgun** [comment]
알려주셔서 감사합니다.
#175 이슈와 동일하게 수정했습니다.
