### ISSUE TITLE
탈퇴된 회원이 계속 로그인 상태 및 권한이 유지되는 보안취약점

### ISSUE THREAD

**Issue by jihan001** [gnuboard/gnuboard5#191]
탈퇴된 회원이 이미 로그인된 세션이 1개이상 있으면 해당 세션이 계속 사용 가능하여 로그인 상태 유지 및 글쓰기 등의 동작이 가능합니다.

새로 로그인할 때만 확인하기 때문에 관리자의 회원에 대한 처리사항이 바로 적용되지 않거나 스스로 탈퇴해도 다른 세션이 남아있다면 유지되는 문제입니다.

회원을 삭제하여 즉시 적용할수 있겠으나 여러 이유로 회원정보를 남겨두어야할수있고 이러한 문제를 보통 인지하지 못할테니 세션을 만료시키는 방안이 적용되어야할 것같습니다.

https://github.com/gnuboard/gnuboard5/blob/c5395a7f44be256b3ba2e77f321d116f20af4062/common.php#L518-L521
여기에서 탈퇴처리 날짜 비교를 추가하면 될것같습니다.

**Comment by KimTom89** [comment]
말씀해주신 부분에 탈퇴처리 날짜 조건을 추가했으며, 해당 내용은 5.5.8 버전에도 반영되었습니다.

알려주셔서 감사합니다. :)
