### ISSUE TITLE
SNS 연동 오류

### ISSUE THREAD

**Issue by HanKaru724** [gnuboard/gnuboard5#194]
SNS연동 시도하였을 때, 만약 SNS에서 받아오는 닉네임에 특수문자(필기체 등) 또는 공백이 포함되어 있으면 "닉네임은 공백없이 한글, 영문, 숫자만 입력 가능합니다."라고 표기됨.

**Comment by thisgun** [comment]
본문의 내용처럼 닉네임에 허용되지 않는 문자열이 있을 경우

닉네임은 input text 란에서 수정하여 가입해야 합니다.

![수정1](https://user-images.githubusercontent.com/4393429/180926532-4b5a1334-5245-4720-bfa7-c12409cffac7.png)
