### ISSUE TITLE
editor 플러그인에서 autosave.js 기능을 사용하고 싶습니다. 

### ISSUE THREAD

**Issue by easylogic** [gnuboard/gnuboard5#20]
summernote(http://summernote.org/) 로 기본 에디터를 변경하고 싶은데요. 

https://github.com/easylogic/gnuboard5-summernote 

관련해서 plugin 을 만들어뒀는데. 

임시저장 기능을 이용할려면 autosave.js  를 직접 하드코딩을 해야하더라구여. 

autosave.js 에 이 부분 추가 가능할까요?

**Comment by chicpro** [comment]
기본으로 제공하지 않는 플러그인에 대해 배포판에 관련없는 코드를 추가하는 것은 어렵습니다.
