### ISSUE TITLE
테마 설정에서 이미지가 영역을 벗어납니다

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#204]
![theme](https://user-images.githubusercontent.com/112419763/199918340-7a8ff096-91df-4a28-a083-a18c9c91b78d.jpg)

테마의 스크린샷 이미지가 너무 크면 밖으로 튀어나감.

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

다음 버전에 아래 내용을 적용하겠습니다.

https://github.com/gnuboard/gnuboard5/commit/589b7f4e3970ad2a4a35ed97f27c58a7fe0b1833
