### ISSUE TITLE
html_process가 초기화 되기전에 js/css 파일을 로드 할수 없습니다

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#206]
`add_javascript()`, `add_stylesheet()` 함수가 html_process 클래스의 인스턴스가 생성되어있지 않으면 js/css 파일을 추가할수 없습니다.
hook, extend, plugin 등에서 js/css 파일을 로드해야할때 실행 시점에 따라 로드가 불가능합니다.

static 메소드로 변경하여 실행 시점에 따라 불능 상태가 되지 않도록 개선되면 좋겠습니다.

지금은 어떠한 경고나 안내도 없이 무시되고 있어서 개발에 혼란이 생깁니다.

개선해주세요.

개선 코드를 반영할 의사가 있으시면 코드 제공하겠습니다.

**Comment by thisgun** [comment]
안녕하세요.
의견 주셔서 감사합니다.

아래 내용으로 다음 버전에 적용하겠습니다.

https://github.com/gnuboard/gnuboard5/commit/62d0bf5c4e2ecf48b53f478cd6e721854a2a6085
