### ISSUE TITLE
set_cookie() 함수로 생성된 cookie가 보호받지 못함

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#208]
https://github.com/gnuboard/gnuboard5/blob/dbc8e1676a4cd3561a74f1d756320a7d82b45bb4/lib/common.lib.php#L146-L152

cookie 이름이나 값을 md5 및 base64 인코딩을 사용해 얼핏 보호하는 듯 되어있으나 매우 낮은 수준의 보호방법이며, 코드가 공개된 특성상 원래의 키나 값을 찾는데 매우 쉬운 구조를 가져서 사실상 전혀 보호되지 않습니다.

쿠키 생성시 클라이언트에서 접근할 필요가 없는 쿠키는 선택적으로 HttpOnly로 설정하여 XSS에 대비할수 있도록해야 합니다.

쿠키의 이름을 md5로 사용한 이상 클라이언트에서 쿠키에 접근하지 않는 것을 가정했다고 보이므로 `set_cookie()` 함수로 생성한 쿠키는 모두 HttpOnly로 설정해도 될것같네요.

**Comment by thisgun** [comment]
안녕하세요.
의견 주셔서 감사합니다.

아래 내용으로 다음 버전에 적용하겠습니다.

https://github.com/gnuboard/gnuboard5/commit/816a32d5c91fb401347fe1dcc797875b09fd34d3
