### ISSUE TITLE
회원 탈퇴할 때 이벤트 추가 요청

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#209]
https://github.com/gnuboard/gnuboard5/blob/dbc8e1676a4cd3561a74f1d756320a7d82b45bb4/bbs/member_leave.php#L15-L21

회원이 탈퇴할 때 로그아웃 직전에 이벤트 실행이 추가되었으면 합니다.
위 코드 21라인에서 세션을 제거하기 전 이벤트 실행이 추가되면 회원 탈퇴 전 로그인된 세션의 회원의 데이터를 정리하는 등의 동작 추가가 수월할 것같습니다. 일부 동작은 회원의 로그인 상태에 의존할수 있으므로 세션 제거 전 실행되면 좋겠네요.

```php
run_event('member_leave', $member);

// 3.09 수정 (로그아웃) 
unset($_SESSION['ss_mb_id']); 
```

**Comment by thisgun** [comment]
안녕하세요.
의견 주셔서 감사합니다.

아래 내용으로 다음 버전에 적용하겠습니다.

https://github.com/gnuboard/gnuboard5/commit/3e53cd8ff6a75a1d674239ee5044198f339b8b59
