### ISSUE TITLE
sql_query() 함수에서 쿼리의 시작/종료시간 반환 문제

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#210]
https://github.com/gnuboard/gnuboard5/blob/dbc8e1676a4cd3561a74f1d756320a7d82b45bb4/lib/common.lib.php#L1626

`sql_query()` 함수 나에서 위와 같이 디버그 모드일때만 시작과 종료 시간을 측정하고있습니다.

디버그 모드가 켜져있지 않으면 쿼리 실행 후 `sql_query_after` hook에 시작과 종료 시간을 넘겨주지 못합니다.

https://github.com/gnuboard/gnuboard5/blob/dbc8e1676a4cd3561a74f1d756320a7d82b45bb4/lib/common.lib.php#L1657

디버그 모드가 아닐때도 쿼리 실행 시간을 측정할수 있도록 개선 바랍니다. 

`get_microtime()` 함수의 부담이 문제라면 `microtime(true)`로 변경하면 됩니다.

**Comment by xperia-query** [comment]
궁금한게있는데요 디버깅을 안하는데 쿼리 실행시간을 측정할필요가 있나요?

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

코드를 제공해 주셔서 대단히 감사합니다.

제안해 주신 코드를 merge 했습니다.
