### ISSUE TITLE
로그아웃하면 pc/mobile 모드 선택이 해제되는 버그

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#216]
방문자가 pc/mobile을 전환했을 때 로그아웃하면 이 설정이 초기화 됩니다.
`$_SESSION['ss_is_mobile']` 세션에 저장되기 때문에 로그아웃할때 세션이 모두 제거되어 방문자의 선택이 무시됩니다.

세션에 저장하는 방식을 바꿔 쿠키로 남기도록 변경해야 방문자의 선택이 유지될 것 같네요.

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

좋은 의견 주셔서 감사합니다.

해당 내용은 메이져 업데이트시 고려하겠습니다.
