### ISSUE TITLE
혹시 jquery 버전 올리실 계획이 있으신가요? 

### ISSUE THREAD

**Issue by easylogic** [gnuboard/gnuboard5#22]
gnuboard 쓰면 기본적으로 jquery 기반이 되어 있어서 따로 jquery 버전을 올리지 않고 쓰고 있긴 한데요. 

bootstrap 라이브러리의 경우 최신 버전 기능을 쓸려면  jquery 1.9.x 대 이상을 써야 하는데. 

gnuboard 쪽은 기본적으로 1.8.x 를 쓰고 있어서  사용할 수가 없는 상태네요.. 

그래서 혹시 계획이 있는지 궁금합니다.

**Comment by chicpro** [comment]
그누보드5에서 제공하는 테마 기능을 사용하는 원하시는 버전의 jquery 를 사용하실 수 있습니다.

**Comment by easylogic** [comment]
답변 감사합니다. 

theme 을 다른 버전으로 사용해야하는군요.
