### ISSUE TITLE
i found a xss vulnerability

### ISSUE THREAD

**Issue by Christynorl** [gnuboard/gnuboard5#224]
hi,@thisgun. I found an xss vulnerability, which may affect the security of all the users. I submitted the specific information in the huntr community, please click the link below to view.
[link to huntr](https://huntr.dev/bounties/cb02ca39-621d-441b-a62c-c41585f2e51b)
https://huntr.dev/bounties/cb02ca39-621d-441b-a62c-c41585f2e51b

**Comment by thisgun** [comment]
Thank you for the information.
