### ISSUE TITLE
관리자 페이지 테마 or 스킨

### ISSUE THREAD

**Issue by gintering1000** [gnuboard/gnuboard5#229]
관리자 페이지(adm폴더)도 사용자페이지처럼 theme or skin 폴더로 코드가 덮어써져서... 업데이트가 되어도 사용자가 개발된 부분이 유지되게 구조를 하나 만들어주실 수 있을까요?
( 코어업데이트 시 관리자페이지 custom 코드 유지 )

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

의견 주셔서 감사합니다.

시간이 굉장히 많이 소요되는 일이라 힘들것 같습니다.
