### ISSUE TITLE
쿠폰 발행 시 UX 오류

### ISSUE THREAD

**Issue by smaker** [gnuboard/gnuboard5#230]
https://github.com/gnuboard/gnuboard5/blob/master/adm/shop_admin/couponmember.php#L48

쿠폰을 발행 시, 회원 검색 팝업에서 회원 이름을 공란으로 하여 검색을 할 수 없습니다. (mb_name에 required 속성이 붙어있습니다.)
회원 이름을 입력했다가, 다시 초기화 할 수 있어야 할 것 같습니다.

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

알려주셔서 감사합니다.

해당 내용을 수정하겠습니다.

**Comment by smaker** [comment]
@thisgun 해결되었는데, 이슈 정리 차원에서 라벨을 좀 붙여주셨으면 좋겠습니다.
그냥 닫아버리면, 이게 해결되었는지 이슈 목록에서 구분이 안 되네요.

**Comment by smaker** [comment]
@kkigomi 기능은 저도 알고 있는데, 라벨이 좀 더 확실하게 구분되는지라 그렇게 했으면 좋겠는데 아쉽네요 😂
