### ISSUE TITLE
설치시 자동생성되는 게시판 글읽기 포인트로 인한 문제

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#231]
최초 설치시 생성되는 게시판의 포인트 설정으로 인해 게시판의 글을 읽을 수 없는 상태로 최초 생성됩니다.
혼란을 방지하기 위해 포인트 설정을 `0`으로 두는 것이 나을 것같습니다.

- 기본환경설정에서 '포인트 사용' 상태
- 기본환경설정에서 게시판 기본 설정에는 포인트가 모두 `0`
- 자동 생성된 게시판(자유게시판, 공지사항 등)이 생성될 때 글 읽기 포인트가 `-1`, 다운로드 포인트 `-20` 등

이처럼 서로 다른 설정으로인해 **포인트** 설정을 인지하고 있지 않으면 방문자나 일반 회원의 글 읽기 등에 제한이 적용된 상태로 운용될 수 있음

https://github.com/gnuboard/gnuboard5/blob/8bcac60bdabe91eb7dc980111da53bd908a0bf3e/install/install_db.php#L288-L291

기본환경설정의 게시판 기본 설정처럼 자동 생성된 게시판의 포인트 설정 또한 `0`을 기본 값으로 가지는 것이 좋을 것 같습니다.

https://github.com/gnuboard/gnuboard5/blob/8bcac60bdabe91eb7dc980111da53bd908a0bf3e/install/install_db.php#L171-L174

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

알려주셔서 감사합니다.

해당 코드를 개선하겠습니다.
