### ISSUE TITLE
list.php 파일에서 g5_latest_cache_data() 함수 사용으로인한 버그

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#232]
https://github.com/gnuboard/gnuboard5/blob/8bcac60bdabe91eb7dc980111da53bd908a0bf3e/bbs/list.php#L174-L208

추정하기로… 게시판 글 목록을 가져오면서 최근글 위젯에 사용할 데이터를 미리 넣어두는 목적으로 사용하는 것으로 보입니다.
tail.php 등에 최근글 위젯이 있다면 이 데이터를 활용할 수 있도록 하기 위함으로 추정합니다.

하지만 `g5_latest_cache_data($board['bo_table'], $list);` 여기에 사용된 `$list`에는 검색 결과의 목록일 수 있어서 최근글 위젯에 잘못된 영향을 줄 수도 있습니다.
캐시를 목적으로 `g5_latest_cache_data()` 함수를 호출로 인해 `g5_latest_cache_data()` 함수가 반환하는 내용이 의도와 다르게 잘못된 데이터가 반환될 수 있어보입니다.

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

해당 코드에 문제점을 찾을수 없었습니다.
