### ISSUE TITLE
게시판 RSS 포맷이 RSS 2.0 스펙에 맞지 않습니다

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#234]
https://github.com/gnuboard/gnuboard5/blob/8bcac60bdabe91eb7dc980111da53bd908a0bf3e/bbs/rss.php#L52
위처럼 테스트하던 코드가 그대로 남아있는 것 같기도하고, 출력되는 포맷 전체가 [RSS 스펙](https://validator.w3.org/feed/docs/rss2.html)에 맞지 않습니다.

날짜 등은 RSS 스펙이 아니라 더블린 코어 스펙의 일부가 혼용되어 있는 등 이게 RSS 스펙에 맞지 않는 문서를 출력하고 있습니다.

스펙을 준수하도록 출력 결과를 수정해야 합니다.

이 문제로 인해 구글 서치 콘솔에서 RSS를 읽지 못합니다.

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

알려주셔서 감사합니다.

해당 내용을 수정했습니다.
