### ISSUE TITLE
저장소에 포함된 의미없는 파일

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#245]
`/extend/user.config.php`
이 파일은 사용자가 설정을 정의하도록 만들어진 파일로 보입니다.

하지만 배포시 이 파일이 포함되어 전체 업데이트시에 파일이 덮어씌워지는 문제가 발생할수있습니다.
사용자의 설정이 몽땅 날아가는 순간이죠.

물론 사용자가 수정한 파일 관리의 책임은 사용자에게 있지만 이 파일은 기본 설정을 제공하는 등 그 어떠한 역할도 하지 못하면서 사용자를 유인하여 이 파일을 활용한다면 의도나 목적과는 다르게 이 사용자를 골탕먹이는 역할만 하게 될뿐 어떠한 긍정적 역할을 하지 못합니다. 이 파일은 저장소에서 제거하는 편이 나을 것같습니다.

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

의견 주셔서 감사합니다.

해당 파일을 삭제했습니다.
