### ISSUE TITLE
몇가지 누락된 스킨관련 

### ISSUE THREAD

**Issue by maxdev-jh** [gnuboard/gnuboard5#25]
안녕하세요, 수고 많으십니다.
그누보드5를 기반으로 작업 중 누락된 테마/스킨 관련기능이 보여서 이슈등록 합니다.

**1. 인증메일 재전송/변경 페이지**
- 이메일 인증이 필요한 사이트에서, 회원가입 후 인증미완료 상태에서 로그인 시도 시 인증메일 주소를 변경할 수 있는 UI를 제공하는 페이지
- /bbs/register_email.php 에서 테마의 스킨을 로드하지 않음으로써, 디자인 변경등을 위해서는 직접 core 코드를 수정해야 하는 문제 발생
- /bbs/register_email.php 라인 21 즈음에 다음과 같은 코드 추가 제안

```
...
$skin_file = $member_skin_path.'/register_email.php';
if( file_exists($skin_file) ) {
    include_once($skin_file);
    include_once('./_tail.php');
    return;
}
...
```

**2. 관리자 > 게시물 이동/복사 팝업 페이지**
- 관리자가 게시물을 이동/복사 할 수 있는 UI를 제공하는 페이지
- /bbs/move.php 에서 테마의 스킨을 로드하지 않음으로써, 디자인 변경등을 위해서는 직접 core 코드를 수정해야 하는 문제 발생
- 마찬가지로, 테마의 board 스킨의 move.php 등을 로드하는 코드가 추가되어야 할 것으로 예상

이상 참고 부탁드립니다.
감사합니다.

**Comment by chicpro** [comment]
문의하신 스킨 추가여부는 현재는 계획이 없습니다.
그누보드5는 오픈소스 프로그램입니다.
필요하시다면 코어의 코드를 수정하셔도 됩니다.

**Comment by maxdev-jh** [comment]
네... 아쉽군요.
사이트 구축할때야 그다지 상관은 없겠지만
빌더나 테마 개발자를 위해서 구조적인 관점에서 좀더 고민해 주시길 바라겠습니다.
