### ISSUE TITLE
관리페이지 메뉴 접근 권한이 부여된 경우 관리페이지의 index 페이지의 정보가 노출되는 문제

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#258]
`환경설정 -> 관리권한설정`(adm/auth_list.php)에서 일반 회원에게 특정 권한을 부여한 경우 관리페이지의 index(/adm/index.php) 페이지의 신규회원 목록, 최근게시물, 최근 포인트 내역 등이 노출됩니다.

이는 회원의 개인정보(이름. 실명)이 노출될 수 있으며, 회원의 포인트 내역과 접근 권한이 제한된(목록, 읽기 권한이 지정된) 게시판에서 작성된 글의 제목 등이 노출될 수 있습니다.

예로:
- 이름 입력이 필수가 아니지만 본인인증을 완료한 경우 실명이 회원정보에 입력되어 노출 됨
- 사이트 매니저들만 사용하는 숨겨 놓은 권한이 제한된 게시판의 글 제목과 글, 댓글 작성자가 노출 됨
- 회원의 포인트 획득 및 누적 현황이 노출 됨
- 그누보드의 정확한 버전이 노출 됨 (관리페이지 footer)

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

의견 주셔서 감사합니다.
