### ISSUE TITLE
저장엔진이 MyISAM으로 하드코딩되어 있어서 불편합니다.

### ISSUE THREAD

**Issue by kijin** [gnuboard/gnuboard5#26]
사이트를 운영하다가 규모가 어느 정도 커지면 단독서버나 클라우드서버로 옮기고 DB도 튜닝을 하게 됩니다. 동접수가 많은 사이트는 테이블 저장엔진을 InnoDB로 변경하는 것으로 성능과 안정성을 개선할 수 있는데요... 서버단에서 일괄 변환해 놓아도 나중에 게시판을 추가하면 또다시 MyISAM 저장엔진으로 생성됩니다.

`common.lib.php`에서 소스를 수정하면 되지만, 업데이트시 매번 다시 바꿔줘야 하기 때문에 가능하면 소스를 수정할 필요가 없는 방향으로 개선되면 좋겠습니다.

`config.php`에서 상수를 하나 정의하고, `get_table_define()` 등의 함수에서 `CREATE TABLE` 쿼리를 작성할 때 이 상수를 참조하도록 하면 편리할 것 같습니다. 기본값은 물론 `MyISAM`으로 해두고요.

아니면 아예 `ENGINE=MyISAM` 구문을 빼버리고, DB에서 지정한 `default_storage_engine`의 값을 따르도록 하는 것도 괜찮겠습니다.

**Comment by thisgun** [comment]
의견 주셔서 감사합니다.

해당 내용을 검토해서 적용하도록 하겠습니다.
