### ISSUE TITLE
영카트 입력값 검증 미흡으로인한 SQL Injection 보안취약점

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#271]
제보내용(비공개): https://sir.kr/co_qa/12741
취약점 제보일 : 2023년 8월 3일

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

알려주셔서 감사합니다.

**Comment by thisgun** [comment]
그누보드(영카트) 5.5.8.3.3 버전에서 아래와 같이 패치 해서 이슈를 닫습니다.

https://github.com/gnuboard/gnuboard5/commit/6868cee8d1f7c0d8b7aa7e8ee98e82ce2fe8cc6d
