### ISSUE TITLE
get_device_change_url() url에 query에 배열이 있을시 에러 발생

### ISSUE THREAD

**Issue by ned3y2k** [gnuboard/gnuboard5#29]
get_device_change_url() url에 query에 배열이 있을시 에러 발생
발생경로
- domain.com/index.php? 에 get_device_change_url()을 사용하는 부분 있다고 가정
- domain.com/index.php?filter[]=1&filter[]=2 로 문서 요청

원본
    if($_SERVER['QUERY_STRING']) {
        foreach($_GET as $key=>$val) {
            if($key == 'device')
                continue;
            $key = strip_tags($key);
            $val = strip_tags($val);
            if($key && $val)
                $q[$key] = $val;
        }

수정제안
    if($_SERVER['QUERY_STRING']) {
        foreach($_GET as $key=>$val) {
            if($key == 'device')
                continue;

            $key = strip_tags($key);

            if(is_array($val)) {
            	foreach ($val as &$element) {
            		$element = strip_tags($element);
	            }
            } else if ($key && $val) {
	            $val = strip_tags($val);
            }

	        if($key && $val)
		        $q[$key] = $val;
        }
    }

**Comment by thisgun** [comment]
해당 내용을 아래와 같이 수정했습니다.

https://github.com/gnuboard/gnuboard5/commit/c7092ee1b331a1642e5310ff2331437c7f4ee2ce
