### ISSUE TITLE
영카트 상품의 짧은주소에 사용되는 `it_seo_title`이 중복되는 문제

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#295]
영카트 상품을 추가, 수정, 복사할 때 짧은 주소에 사용되는 `it_seo_title` 값의 중복방지처리를 하지 않아 주소 중복이 발생하는 문제입니다.

상품을 추가, 수정, 복사할 때 `it_seo_title` 값이 중복되지 않고 고유한 값으로 생성하여 이 문제를 해결해야 합니다.

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

알려주셔서 감사합니다.

다음 패치 때 아래와 같이 수정하겠습니다.

https://github.com/gnuboard/gnuboard5/commit/1fc3a343c270db15f0997a09d46182ef440082c3
