### ISSUE TITLE
잘못된 정규표현식 처리로 인해 위장 도메인으로 iframe 태그가 허용되는 보안취약점

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#297]
제보내용: https://sir.kr/co_qa/13271

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

알려주셔서 감사합니다.

다음 패치에 아래와 같이 수정하겠습니다.

https://github.com/gnuboard/gnuboard5/commit/4f2f725de8c9e87569391fe05075ba03c4dc625c
