### ISSUE TITLE
게시판 아이디를 `content`로 생성하면 짧은주소 기능과 충돌하는 문제

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#299]
https://github.com/gnuboard/gnuboard5/blob/5605b539f4438d5b261937fa3ec631b5f0c573a0/lib/get_data.lib.php#L395-L404

게시판을 `content`로 생성하면 "내용관리" 기능과 충돌합니다.

기본 rewrite 설정으로는 "내용관리"가 우선하고, `/content`는 `content` 게시판 목록이 표시되나 글 쓰기 페이지(`/content/write`) 주소 등으로 인해 충돌이 발생합니다.

게시판 생성 시 `content`를 사용할 수 없도록 제한할 필요가 있어 보입니다.

```php
function get_bo_table_banned_word(){

    $folders = array('content');
    // ...
}
```

또한, `rss`도 기본 rewrite에 포함되어 있기 때문에 `rss`도 제한하는 것을 고려해봐야 할 것 같네요.

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

알려주셔서 감사합니다.

그누보드(영카트) 5.5.11 버전에 해당 내용을 적용했습니다.
