### ISSUE TITLE
비밀댓글 열람 기준

### ISSUE THREAD

**Issue by Mabin-J** [gnuboard/gnuboard5#30]
비밀댓글 열람기준이 이상합니다.

현재는 글 작성자만 글의 모든 비밀댓글을 열람할 수 있도록 되어있습니다.

댓글에 대해 비밀대댓글을 작성하는 경우,
보통 댓글 작성자만 볼 수 있게 할 의도록 비밀대댓글을 작성할텐데,
정작 보아야할 댓글 작성자에게는 댓글이 보이지 않고,
글 작성자만 비밀대댓글을 볼 수 있게 됩니다.

다음과 같이 댓글이 작성되어있다고 가정해봅시다.
- 원글, 일반, 사용자1
    - 댓글1, 비밀, 사용자2
    - 댓글2, 일반, 사용자2
        - 댓글2-1, 일반, 사용자3
            - 댓글2-1-1, 비밀, 사용자2
        - 댓글2-2, 비밀, 사용자3
        - 댓글2-3, 일반, 사용자3
        - 댓글2-4, 비밀, 사용자1
    - 댓글3, 일반, 사용자3
    - 댓글4, 비밀, 사용자3

이런 구조로 댓글이 작성 되어있다고 했을 때,
사용자1가 볼 수 있는 댓글은 1, 2, 2-1, 2-3, 2-4, 3, 4
사용자2가 볼 수 있는 댓글은 1, 2, 2-1, 2-1-1, 2-2, 2-3, 2-4, 3
사용자3이 볼 수 있는 댓글은 2, 2-1, 2-1-1, 2-2, 2-3, 3, 4
이 되어야할 것 같습니다.

**Comment by thisgun** [comment]
의견 주셔서 감사합니다.

해당 내용을 검토해서 적용하도록 하겠습니다.
