### ISSUE TITLE
darkmode 브랜치는 병합될 예정인가요?

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#303]
`feature/darkmode` 브랜치에서 기본 테마 및 관리페이지에 다크모드 작업이 되어있는데, master 에 병합될 예정인가요?

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

아직 미흡한 부분이 있어서, 차후에 다시 진행하도록 하겠습니다.
