### ISSUE TITLE
문법 오타 제보합니다

### ISSUE THREAD

**Issue by beaverfactory** [gnuboard/gnuboard5#310]
안녕하세요! 
오늘 하루도 그누보드 커스텀 삼매경에 빠져 사는 개발자입니다.
작업 하는 도중에 오타를 발견해서요
[adm/faqmasterformupdate.php](https://github.com/gnuboard/gnuboard5/blob/master/adm/faqmasterformupdate.php)

여기 소스코드를 보게 되면 

$sql = " alter table {$g5['faq_master_table']} auto_increment=1 ";
sql_query($sql);

이게 필요 없지 않을까요?? 그거랑 바로 아래에 소스코드보면 

$sql = " insert {$g5['faq_master_table']} $sql_common ";
sql_query($sql); 

뭔가 쿼리가 잘못 된거 같아서요 insert into 로 수정 해야될것같아요.
별거 아니지만.. 제보 해야될것 같아서 글남깁니다. 수고 하십쇼 ㅎㅎㅎ

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

의견 주셔서 감사합니다.

alter table 구문은 지금 쓰고 있는 버전 사용자에게는 필요없는 코드이지만, 옛날에 특정버전을 사용하는 자들에게는 필요한 코드입니다.

mysql 에서 insert set 쿼리문도 지원하니, 수정하지 않겠습니다.

**Comment by beaverfactory** [comment]
글 봐주셔서 감사합니다~~  😀
