### ISSUE TITLE
최신그누보드) 게시판 관리 목록 훅 이슈 문제

### ISSUE THREAD

**Issue by beaverfactory** [gnuboard/gnuboard5#313]
안녕하세요! 매번 그누보드 작업 삼매경에 빠져 있는 개발자 입니다.
이번에 최신버전으로 작업 하다가 발견 했는데요
관리자 페이지에서 게시판 관리에서 목록 페이지입니다.  /adm/board_list_update.php 

맨하단에 보면 run_event 훅 있는데 근데 훅이 run event 가 아니라 replace 가 아닐까 생각해서 수정했는데 
예측 대로 맞더라구요 
맨 하단 위치를 변경 하였습니다.
if ($act_button === "선택수정") { 조건문에서 끝나는 시점에서 
run_replace('admin_board_list_update', $act_button, $post_count_chk,$chk, $post_board_table); 를 넣었구요

} elseif ($act_button === "선택삭제") { 조건문 끝나는 시점에서 
run_replace('admin_board_list_delete', $act_button, $post_count_chk,$chk, $tmp_bo_table); 를 넣었습니다.

여기서 선택 수정은 제가 테스트 해봐서 작동됐는데 삭제도 부분도 아마 맞을거 같아요 

/adm/board_form_update.php 에서 run_event('admin_board_form_update', $bo_table, $w); 는 잘 작동됩니다.
여기는 문제 없는데 목록에서 이슈가 있다보니.. 제보 드립니다. 확인 해보시고 개선 부탁드립니다.

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

해당 코드에 문제점을 발견할수 없었습니다.

**Comment by beaverfactory** [comment]
> 안녕하세요. SIR 입니다.
> 
> 해당 코드에 문제점을 발견할수 없었습니다.

근데 저는 계속 run_event로 했을때 동작이 되지 않아서.. 그냥 바꿔서 쓰니까 동작해서 그러고 쓰고 있어요..

**Comment by thisgun** [comment]
> > 안녕하세요. SIR 입니다.
> > 해당 코드에 문제점을 발견할수 없었습니다.
> 
> 근데 저는 계속 run_event로 했을때 동작이 되지 않아서.. 그냥 바꿔서 쓰니까 동작해서 그러고 쓰고 있어요.. 아니면 사용법이라도 좀 제대로 알려주시면 감사하겠습니다..

run_event 하기 전에

add_event 로 사용할 함수 등록하면 됩니다.

extend 폴더의 아무 파일에 아래 코드를 입력하면,
게시판 관리 목록에서 수정이나 삭제시 run_event('admin_board_list_update') 할때 아래 내용이 실행됩니다.

```
add_event('admin_board_list_update', 'fn_admin_board_list_update', 1, 4);

function fn_admin_board_list_update($act_button, $chk, $board_table, $qstr) {

    print_r($act_button);
    print_r($chk);
    print_r($board_table);
    print_r($qstr);

    exit;
}
```
