### ISSUE TITLE
`HTMLPurifier_Filter_iframevideo` 클래스명의 대소문자 불일치

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#324]
https://github.com/gnuboard/gnuboard5/blob/9c44d234ed44b84ed8ab0e8d3f9e1dc2dd1a2e24/plugin/htmlpurifier/extend.video.php#L10-L11

https://github.com/gnuboard/gnuboard5/blob/9c44d234ed44b84ed8ab0e8d3f9e1dc2dd1a2e24/lib/common.lib.php#L661

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

알려주셔서 감사합니다.

해당 내용을 수정했습니다.
