### ISSUE TITLE
초기화되지 않은 `$cache` 변수

### ISSUE THREAD

**Issue by kkigomi** [gnuboard/gnuboard5#325]
https://github.com/gnuboard/gnuboard5/blob/9c44d234ed44b84ed8ab0e8d3f9e1dc2dd1a2e24/lib/get_data.lib.php#L144-L185

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

알려주셔서 감사합니다.

해당 내용을 수정했습니다.
