### ISSUE TITLE
feat/restapi > 게시글의 댓글에서 일부 필드가 값이 미반영

### ISSUE THREAD

**Issue by Junanjunan** [gnuboard/gnuboard5#333]
/api/v1/boards/{bo_table}/writes/{wr_id} 게시글 조회

위 API에서 mb_image_path, mb_icon_path, save_content, is_secret 등의 값이 실제와 다르게 반영 (빈값 또는 default false)

![image](https://github.com/user-attachments/assets/39dbd6d2-f939-43d0-87e8-2d835599e169)

**Comment by kitrio** [comment]
추가 완료
