### ISSUE TITLE
[rest-api] 토큰 발급 500에러 발생

### ISSUE THREAD

**Issue by humorous-app** [gnuboard/gnuboard5#335]
1. https://api.gnuboard.com/api/v1/token
2. https://humorous.co.kr/api/v1/token
3. https://humorosday.com/api/v1/token

1번은 sir에서 제공되는 테스트 서버 - 에러

2번은 기존 그누5를 이용하여, api만 추가한 서버 - 에러

3번은 rest-api 에서 코드 그대로 다운로드 받아 설치 한 서버 - 에러

토큰 발급 시도 시 500에러가 발생합니다.

추가) 리프레시 토큰도 일단 그냥 500에러가 출력됩니다.

![Honeycam 2024-08-22 12-45-33](https://github.com/user-attachments/assets/05d97538-9e25-4326-8240-29b9ddc08e47)

**Comment by kitrio** [comment]
리프레시 토큰테이블 생성관련된 문제였습니다. 수정했습니다.

**Comment by humorous-app** [comment]
@kitrio 잘 됩니다. 고맙습니다.
