### ISSUE TITLE
[rest-api][건의] API 만 사용 + 관리자는 접근 가능

### ISSUE THREAD

**Issue by humorous-app** [gnuboard/gnuboard5#336]
글을 쓸까? 말까 고민 하다, 건의 글 남겨봅니다.

위 기능은 기존 그누보드6에 있던 기능으로

API 만 사용할 수 있는 기능이 있었습니다. (설정으로 온오프 기능) 

그럼 기본 화면은 출력되지 않는 기능이였죠

다만, API 를 사용하더라도 예외적으로 관리자 화면은 접속이 가능했는데요

이 기능을 그누5에도 넣어주실 수 있을까요 ??

설정은 그누5 관리자 화면 혹은 .env 파일에 넣어도 될꺼 같구요 (기존 그누6가 .env)

**Comment by kagla** [comment]
> 글을 쓸까? 말까 고민 하다, 건의 글 남겨봅니다.
> 
> 위 기능은 기존 그누보드6에 있던 기능으로
> 
> API 만 사용할 수 있는 기능이 있었습니다. (설정으로 온오프 기능)
> 
> 그럼 기본 화면은 출력되지 않는 기능이였죠
> 
> 다만, API 를 사용하더라도 예외적으로 관리자 화면은 접속이 가능했는데요
> 
> 이 기능을 그누5에도 넣어주실 수 있을까요 ??
> 
> 설정은 그누5 관리자 화면 혹은 .env 파일에 넣어도 될꺼 같구요 (기존 그누6가 .env)

개발이 완료될 시점에 지원될 예정입니다.
감사합니다.

**Comment by humorous-app** [comment]
@kagla 이슈 닫을께요 답변 고맙습니다.
