### ISSUE TITLE
[rest-api] 게시판 내 데이터 출력에 관한 건의

### ISSUE THREAD

**Issue by humorous-app** [gnuboard/gnuboard5#337]
게시판 내 출력 부분 관련 

- 아이디는 사이드 뷰 때문에 그렇다 치지만, 이메일 정보 / 아이피 정보가 전체가 그대로 노출 됩니다.

- 프론트에서 ** 처리 하는 것이 어려운 게 아니라, 실제 api 경로를 알고 get 형태로 출력만 하면 그대로 100% 원본이 나오는데 프론트에서 ** 처리가 의미  있을지 의문입니다.

- 개인적으론 아이디도 어떻게 처리했으면 하지만, 아이디어가 떠오르진 않습니다-_-; 아니면 아스키 코드나 해싱 해서 데이터 보내서, 받는 쪽에서 해싱해서 서로 연동하면 아이디 노출도 보완되고 좋을텐데 말이죠

예) abcd.com/api/v1/boards/free 하면 게시판 내 데이터가 그대로 노출되니깐요 

실제 페이지 total_pages 보다 높게 입력 시 에러 반환 하지 않음 

예) .abcd.com/api/v1/boards/free?page=10000000 

 ※ 게시글 보기도 마찬가지입니다. (다른 곳은 아직 안봤습니다)

**Comment by kitrio** [comment]
사이드뷰 (게시글 목록, 게시글, 댓글의 작성자등)  표시할때 사용하는 API 들에서
그누보드 5 템플릿과 동일하게  IP , 이메일 정보를 가리게 수정 중입니다.

* IP - config.php 의 상수로 일부 숨깁니다.
* 이메일 - str_encrypt 를 openssl 로 대신하여 서버에서 암호화된 값으로 표시하게됩니다.

감사합니다.

**Comment by kagla** [comment]
관리자는 아이피를 모두 보여주고, 그 외 방문객은 아이피를 일부 가리면 되지 않을까요?
