### ISSUE TITLE
[rest-api] 게시글 등록 시 500에러 반환

### ISSUE THREAD

**Issue by humorous-app** [gnuboard/gnuboard5#338]
![Honeycam 2024-08-29 10-13-11](https://github.com/user-attachments/assets/46a1942a-d04a-4cdd-8ef2-8e4b48f81fbe)

500에러 반환은 되지만, 실제 게시글은 등록됩니다.

P.S. 필수 등록이 너무 많은 듯한 느낌

![image](https://github.com/user-attachments/assets/51ee5bf8-2b99-4cac-8ff7-4dcc91a7350e)

홈페이지 / 링크 / 옵션 이런건 필수 등록 안해도 되지 않을까 싶습니다.

아마 회원과 비회원 기준인 것 같은데, 확인해주세요

**Comment by kitrio** [comment]
필수 조건
회원     - 제목, 내용
비회원 - 제목, 내용, 작성자만 추가로 수정했습니다.

내용이 html 일 경우 문자열로 html1 또는 html2 를 지정해야합니다.
기존 그누보드 5 에서 읽기 위함입니다.

html1 - html 그대로 출력
html2 - \n 을 <br> 태그로 변환합니다.

html 적용시 html1 을 주로 사용합니다.
