### ISSUE TITLE
[rest-api] 게시글 수정 시 500에러 반환

### ISSUE THREAD

**Issue by humorous-app** [gnuboard/gnuboard5#339]
![Honeycam 2024-08-29 10-17-29](https://github.com/user-attachments/assets/7a4c73a1-459d-4f5e-a4d9-10f141bf62a4)

게시글 수정 500에러 반환 하며, 실제 게시글은 수정 됩니다.

타인의 게시글을 강제로 수정 해보려 해도 500에러가 발생합니다. (권한 오류가 아님)

**Comment by kitrio** [comment]
안녕하세요 SIR 입니다.

500 에러 관련해서 답변드립니다.
403 이 반환되고 있으나 Http 핸들러에서 500으로 반환하고있었습니다.
또한 게시글 수정시 배열의 없는 값 접근으로 인해 500 에러가 발생했습니다.

해당 건은 
[fix]  REST API > 게시글 일부 필드 누락시 작성 불가 오류 수정
https://github.com/gnuboard/gnuboard5/commit/6a84be5a0afbd6b617d9903fe062b2601221c274

[fix] REST API> Shutdown 핸들러 notice, warning 제외
https://github.com/gnuboard/gnuboard5/commit/09b7d40b99fc01e44f31057a5de383c82f3bec4f
에서 수정되었습니다.
