### ISSUE TITLE
[rest-api] 현재 로그인 한 회원 정보 오류 / 회원 포인트 오류

### ISSUE THREAD

**Issue by humorous-app** [gnuboard/gnuboard5#340]
![Honeycam 2024-08-29 14-16-55](https://github.com/user-attachments/assets/32a5f78c-dff0-4193-8f59-d663b91377bf)

억세스 토큰이 있던 / 없던 무조건 에러 납니다.

![image](https://github.com/user-attachments/assets/9b2e6c51-4c52-4461-bdce-4c5437bce09f)

여기도 오류 나네요

**Comment by kitrio** [comment]
Content-Type 을 application/json 으로 지정 후 전송 데이터가 빈값일 때 발생하는 오류 였습니다

빈값일 때 더 이상 json 오류가 발생하지 않게 수정했습니다.

**Comment by humorous-app** [comment]
@kitrio 감사합니다.
