### ISSUE TITLE
[rest-api] 게시판정보 부분 스킨정보, 썸네일 출력관련 건의 

### ISSUE THREAD

**Issue by waanee** [gnuboard/gnuboard5#342]
안녕하세요
그누보드 rest api 를 테스트 하며 사용해 보고 있습니다. 

게시판 정보를 가져오는 
/api/v1/boards/{bo_table} API 에서 bo_skin 을 추가 하여 게시판이 어떤 스킨정보 인지 알 수 있으면 좋을것 같습니다. 

앱으로 구현시, 각 게시판 마다 앱에서 리스트스타일이나, 표시방법을 각 스킨 마다 다르게 표시 한다면 게시판 스킨정보를 확인해서 
리스트 스타일을 다르게 표시 할 수 있을거 같아요 

그리고, 게시판 리스트를 출력 할때, 썸네일 정보가 표시 안되어 있던데 이 부분은 아직 구현이 안되어 임시로 있는 부분 인거죠?
썸네일 부분도 기능이 구현 되었으면 좋겠습니다. 리스트 표시중 썸네일 이미지가 있는 경우 썸네일을 표시 하면 앱의 화면이 더 좋을것 같습니다.

**Comment by kitrio** [comment]
안녕하세요 SIR 입니다.

의견주셔서 감사합니다.

1. 썸네일 출력은 수정중입니다.
2. bo_skin, bo_mobile_skin 항목은 
기존에도 css , js 경로 , 페이지 하단등으로 노출되고 있던 정보여서 추가하겠습니다.

**Comment by waanee** [comment]
감사합니다!
