### ISSUE TITLE
[rest-api] 그룹리스트, 그룹게시판리스트 정렬 관련 건의 

### ISSUE THREAD

**Issue by waanee** [gnuboard/gnuboard5#343]
안녕하세요.
API 중 BoardService.php, GroupService.php 에서 리스트 정렬중 환경설정에서 출력순서를 API 에서도 반영 되었으면 해서 해당 내용을 남깁니다.

BoardService.php (41 Line)
public function fetchBoardsByGroupId(string $gr_id)
  {
      $query = "SELECT * FROM {$this->table} WHERE gr_id = :gr_id";
      $stmt = Db::getInstance()->run($query, ['gr_id' => $gr_id]);
      return $stmt->fetchAll();
  }

에서 
public function fetchBoardsByGroupId(string $gr_id)
  {
      $query = "SELECT * FROM {$this->table} WHERE gr_id = :gr_id ORDER BY bo_order";
      $stmt = Db::getInstance()->run($query, ['gr_id' => $gr_id]);
      return $stmt->fetchAll();
  }

ORDER BY bo_order 가 추가 되었으면, 좋을것 같습니다. 

GroupService.php (23 Line)
public function fetchGroups()
  {
      $query = "SELECT * FROM {$this->group_table} ORDER BY gr_id";
      $stmt = Db::getInstance()->run($query);

      return $stmt->fetchAll();
  }

public function fetchGroups()
  {
      $query = "SELECT * FROM {$this->group_table} ORDER BY gr_order";
      $stmt = Db::getInstance()->run($query);

      return $stmt->fetchAll();
  }

위 내용에서 gr_order 기준으로 출력순서를 변경 하면 출력 순서에 맞게 리스트가 출력 가능 할것 같습니다. 
만약 앱에서 해당 그룹을 순서대로 출력시, 해당 순서로 나열을 하면, 환경설정에서 설정한 출력순서대로 나오도록 수정이 되면 더 좋을것 같습니다.

**Comment by kitrio** [comment]
안녕하세요. SIR 입니다.

알려주셔서 감사합니다.

수정하였습니다.

**Comment by waanee** [comment]
수정 감사합니다!
