### ISSUE TITLE
[rest-api] 현재 접속자 API 건의

### ISSUE THREAD

**Issue by humorous-app** [gnuboard/gnuboard5#345]
그누보드5 / 그누보드6에 모두 내장되어있는

현재 접속자 기능이 현재 REST API 자체 내 존재하지 않는 것으로 보여집니다.

해당 기능 자체가 그누5에 있는 만큼 만들어주시면 좋을 것 같아 건의 드립니다.

**Comment by kitrio** [comment]
안녕하세요 sir입니다. 


추가했습니다.
