### ISSUE TITLE
[rest-api] 현재 접속자에서 회원 정보를 불러 올 수 없습니다.

### ISSUE THREAD

**Issue by humorous-app** [gnuboard/gnuboard5#346]
![Honeycam 2024-10-04 10-58-16](https://github.com/user-attachments/assets/e6c4072d-29ac-478a-94d4-b2272a3dc673)

현재 접속자 추가가 잘되지만, 회원의 경우는 회원 정보가 불러오지 않습니다. 
스웨거에서 로그인 > 현재 접속자 추가 > 확인 절차입니다.

**Comment by kitrio** [comment]
안녕하세요 sir 입니다.

알려주셔서 감사합니다.

openapi 주석에서 security={{"Oauth2Password": {}}}, 이 누락되면 스웨거에서 로그인을 해도 인증이 안됩니다.
수정되었습니다.
