### ISSUE TITLE
composer.json 의 오타로 인해 업데이트 안됩니다.

### ISSUE THREAD

**Issue by humorous-app** [gnuboard/gnuboard5#348]
![스크린샷 2024-10-11 153950](https://github.com/user-attachments/assets/b1093598-f234-4100-b85c-18aef8135f9d)
![스크린샷 2024-10-11 154022](https://github.com/user-attachments/assets/da50eb23-ff5a-40b0-899f-d8771bbc1646)
![스크린샷 2024-10-11 154102](https://github.com/user-attachments/assets/2da90315-0fa1-4007-b605-d2408160b02d)

두번째 스샷 보시면 아시겠지만,  "phpmailer/phpmailer": "^6.9",  <== 콤마 들어가서 업데이트 안됩니다.
제거 시 정상 업데이트 됩니다.

**Comment by kitrio** [comment]
안녕하세요 sir 입니다.

수정하였습니다.
감사합니다.
