### ISSUE TITLE
사용 및 설치 오류

### ISSUE THREAD

**Issue by comjun04** [gnuboard/gnuboard5#39]
어느 순간부터 그누보드 5.3.1.7에서 게시판 추가/수정 및 일부 게시판의 글 쓰기가 안 되는 것을 발견했습니다.
데이터베이스를 확인해보니 `g5_write_<게시판id>` 테이블은 생성되어지는데 목록 테이블 `g5_board`에 등록이 되지 않습니다.

그래서 데이터베이스를 새로 만들고 새로 설치를 했더니...

> 그누보드5 설치가 시작되었습니다.
전체 테이블 생성 완료
insert into `g5_config` set cf_title = '그누보드5', cf_theme = 'basic', cf_admin = 'admin', cf_admin_email = 'admin@domain.com', cf_admin_email_name = '그누보드5', cf_use_point = '1', cf_use_copy_log = '1', cf_login_point = '100', cf_memo_send_point = '500', cf_cut_name = '15', cf_nick_modify = '60', cf_new_skin = 'basic', cf_new_rows = '15', cf_search_skin = 'basic', cf_connect_skin = 'basic', 
(중간생략)
cf_member_img_height = '60', cf_login_minutes = '10', cf_image_extension = 'gif|jpg|jpeg|png', cf_flash_extension = 'swf', cf_movie_extension = 'asx|asf|wmv|wma|mpg|mpeg|mov|avi|mp3', cf_formmail_is_member = '1', cf_page_rows = '15', cf_mobile_page_rows = '15', cf_cert_limit = '2', cf_stipulation = '해당 홈페이지에 맞는 회원가입약관을 입력합니다.', cf_privacy = '해당 홈페이지에 맞는 개인정보처리방침을 입력합니다.'

> 1364 : Field 'cf_add_script' doesn't have a default value

> error file : /install/install_db.php

이렇게 뜹니다.
오류가 난 파일로 찾아가서 쿼리문을 mysql에 그대로 쳐도 결과는 똑같습니다.
오류가 난 `cf_add_script` 필드를 임의로 초기화해주니 또 `cf_add_meta`에서 똑같은 오류가 납니다.

`install/gnuboard5.sql` 파일에 데이테베이스 구조가 나와있는 것 같은데,
그 파일이랑 충돌이 있다고 생각합니다.

이 이유로 지금 그누보드5 못 돌리고 있습니다.
빨리 다음 버전에서 해결해 주시기 바랍니다.

**Comment by comjun04** [comment]
확인결과 `gnuboard5.sql` 파일에서 정의된 테이블 필드를 모두 정의해 줘야 정상 작동합니다.
일단 설치 부분은 어떻게든 해결했지만, `adm`(관리페이지)과 `bbs`(게시판 소스)는 소스가 너무 많아 수정을 못 하고 있습니다.

최대한 빨리 패치해 주시기 바랍니다.

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

해당 부분은 수정해야 할 부분이 많아서 단기간에 쉽게 수정할수 없습니다.

다른 일정이 있기 때문에, 당분간은 해당 내용의 수정이 어려울것 같습니다.

도움이 못되어 죄송합니다.
