### ISSUE TITLE
Some security vulnerabilities in v5.3.2.8

### ISSUE THREAD

**Issue by LoRexxar** [gnuboard/gnuboard5#43]
Some security vulnerabilities in v5.3.2.8

- limited Reflective xss in bbs/login.php
- Reflective xss in bbs/move_update.php
- SQL injection in install_db.php

the details of these vulnerabilities to see

https://github.com/LoRexxar/CVE_Request/tree/master/gnuboard5%20mul%20vuls%20before%20v5.3.2.8

**Comment by thisgun** [comment]
Thank you for your information.

**Comment by LoRexxar** [comment]
Maybe it was fixed in some past version, it's been so long that I can't be sure of the specifics

**Comment by zentery** [comment]
@thisgun The patch here seems to be modified incorrectly. The install_db.php can directly POST to receive table_prefix, but the patch modification of install/ajax.install.check.php is out of sync with install_db.php.
