### ISSUE TITLE
5.4에서 댓글 이벤트에 코멘트 아이디도 같이 보내줬으면 합니다.

### ISSUE THREAD

**Issue by choiks14** [gnuboard/gnuboard5#44]
write_comment_update.php에서 run_event시에 wr_id랑 comment_id도 같이 추가 되었으면 합니다. 
comment_update_after 이벤트 받아서 어떤 코멘트가 작성되었는지 필요할듯 합니다. 
검토 부탁드립니다. 
항상 감사합니다. ^^

---
기존

``
run_event('comment_update_after', $board, $wr_id, $w, $qstr, $redirect_url); 
``

---
수정

``
run_event('comment_update_after', $board, $wr_id,$comment_id, $w, $qstr, $redirect_url); 
``

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

의견 주셔서 감사합니다.

이미 hook 이벤트를 사용하는분들도 있을것 같으므로 아래와 같이 수정하겠습니다.
`
run_event('comment_update_after', $board, $wr_id, $w, $qstr, $redirect_url, $comment_id);
`

**Comment by choiks14** [comment]
감사합니다. ^^
