### ISSUE TITLE
mysql이 업데이트 되면서 PASSWORD 함수 삭제됨.

### ISSUE THREAD

**Issue by sdrstone1** [gnuboard/gnuboard5#45]
[여기](https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html#function_password)에 따르면
PASSWORD()
This function was removed in MySQL 8.0.11.
라고 하네요.

처음 설치할 때 ./gnuboard5/install/install_db.php에서 발생하구요.
sha2('$비밀번호',512);정도로 대체 가능할 것 같습니다.

로그인에도 바꿔야 할 것 같습니다.(로그인은 어떤 파일에서 처리하는지 모르겠네요...)

**Comment by thisgun** [comment]
5.4 버전부터

PBKDF2(Password-Based Key Derivation Function) 으로 바뀐다고 안내했습니다.

https://sir.kr/g5_pds/4578

**Comment by sdrstone1** [comment]
감사합니다! 제가 못봣네요!
