### ISSUE TITLE
bbs/move_update.php > HOOK 추가 건의

### ISSUE THREAD

**Issue by angelbro** [gnuboard/gnuboard5#49]
에디터 업로드 이미지를 파일 복사,이동시 첨부파일처럼 함께 복사, 이동 되도록  작업중입니다.
코어를 수정하지 않고 할 수 있는 방법이 없더군요.
5.4부터 HOOK 기능이 생겨 유용하게 사용하고 있는데 기왕이면 그누보드의 여러 곳에서 HOOK의 사용이 가능하면 좋겠습니다. (아마 지금도 여러 곳에서 조금씩 더 늘어나겠지만요..)

현재의 코어 구조는 파일의 복사(이동)시 여러 게시판으로 복사(이동)하는 경우나 원글에 코멘트가 있는 경우 타겟되는 게시판의 wr_id를 가져올 수가 없습니다.
move_update.php의 run_event('bbs_move_update', $bo_table, $chk_bo_table, $wr_id_list, $opener_href);
HOOK 이전에 처리하게 되어 있는 구조라서 그렇지요.
현재의 파일 구조라면 197라인 또는 191라인 위로 HOOK이 있으면 while문이 닫히기 전에 전처리로 가능할 것 같습니다.

업데이트를 준비하면서 한 번 참고해주시면 좋겠습니다.

**Comment by thisgun** [comment]
의견 주셔서 감사합니다.

조만간 해당 내용에 대해서 패치하겠습니다.
