### ISSUE TITLE
update from 5.3 to 5.4

### ISSUE THREAD

**Issue by gfvh** [gnuboard/gnuboard5#50]
Hello

How to upgrade 5.3 to 5.4? Can i do this by just replacing files or there is db update needed and if yes, then how? Is there update tool perhaps?

i am very thankful for any help

**Comment by thisgun** [comment]
1. git pull origin master;

2. 
![1](https://user-images.githubusercontent.com/4393429/75733866-c6ea8a00-5d39-11ea-863d-e2f06c48689d.png)
