### ISSUE TITLE
게시판별로 에디터를 따로 사용가능하게 부탁드립니다.

### ISSUE THREAD

**Issue by jakekwak** [gnuboard/gnuboard5#55]
마크다운 에디터를 적용시켜 볼려고 했는데, 아직 호환성에 문제가 있습니다.

그래서 각 게시판별로 에디터를 설정할수 있게 부탁드립니다.

단순하게 생각해 보면 bo_use_dhtml_editor를 예를 들면..
`0: 사용안함.`
`1: cheditor`
`2: smarteditor 식으로.`

순서는 `plugin/editor`에서 읽어 오는 순서로..

**Comment by woosungchoi** [comment]
이거 좋네요. 아미나에서는 기본 설정이지만요.

**Comment by thisgun** [comment]
안녕하세요. SIR 입니다.

의견 주셔서 감사합니다.

해당 내용은 그누보드5 5.4.2.8 버전에 적용하겠습니다.

**Comment by woosungchoi** [comment]
다행이네요!

**Comment by sundoforce** [comment]
@woosungchoi 
@thisgun 
감사합니다

**Comment by jakekwak** [comment]
https://github.com/gnuboard/gnuboard5/commit/3e04f1403fcedc8a970f13514580ddba86cbceb5
과 https://github.com/gnuboard/gnuboard5/commit/4648b497113af408133b259d8aea8a9c16fb7f9a 로 수정되었습니다.
