### ISSUE TITLE
댓글에 이미지 업로드 기능 해주시면 안될까요?

### ISSUE THREAD

**Issue by sundoforce** [gnuboard/gnuboard5#57]
안녕하세요
그누보드 너무 잘 사용하고 있습니다.

댓글에 이미지 업로드 하는 기능 default로 
혹시 여유가 되시면

차후 패치에 기능 포함 시켜주실수 있나요?

**Comment by woosungchoi** [comment]
그누보드 차원에서 가능하면 최고라고 생각합니다.

**Comment by sundoforce** [comment]
@woosungchoi 

ㅎㅎ 지금 봤네요

**Comment by sundoforce** [comment]
@thisgun 
부탁드립니다

**Comment by thisgun** [comment]
안녕하세요.

좋은 의견 감사합니다.

마이너업데이트 시 고려해 보겠습니다.

**Comment by woosungchoi** [comment]
@thisgun 기대됩니다!

**Comment by sundoforce** [comment]
@thisgun 감사합니다~
