### ISSUE TITLE
태그 지원

### ISSUE THREAD

**Issue by jakekwak** [gnuboard/gnuboard5#59]
요즘 대세가 태그를 지원하고 있습니다.

그누보드 순정에서 지원을 안하다 보니,  각자가 만들어서 사용을 하고 있는 것 같습니다.

별도로 만들어 볼까하다가,  이번 기회에 그누보드 순정에서도 태그를 지원했으면 합니다.

**Comment by woosungchoi** [comment]
적극 동감합니다. 커뮤니티나 블로그 모두 유용하다고 생각합니다.

**Comment by kagla** [comment]
답변이 늦었습니다.
SIR 사이트에는 적용이 되어 있으나 그누보드5 순정에는 적용하기가 쉽지 않아 보입니다.
수월한  방법이 있는지 검토해 보겠습니다.
