### ISSUE TITLE
로그인 횟수 제한 제안

### ISSUE THREAD

**Issue by girlsapink** [gnuboard/gnuboard5#60]
요며칠 그누보드로 운영하는 사이트에 계정 탈취 목적인지
계정에 로그인 시도가 계속 이루워지고있네요.
xe 이용할댄 기본으로 로그인횟수 제한이라는 기능이 있어 관리자 페이지에서
설정해놓은 횟수 초과하면 일정시간 로그인 제한 또는 해당 ip 차단이 되는데
그누보드는 그런기능이 없더군요.
혹시나 이부분에 대해 고려좀 해주시기 바랍니다.

**Comment by woosungchoi** [comment]
커뮤니티의 기본 기능이라고 생각합니다.

코어에 꼭 필요한 기능입니다.

**Comment by kagla** [comment]
답변이 늦었습니다.
제 개인적으로 생각해서 처리하는 것보다는 여러 분들의 의견을 들어보는 것이 좋겠다는 생각에서 QA에 글을 등록해 놓았습니다.
https://sir.kr/qa/453292
