### ISSUE TITLE
class.phpmailer.php > public $SMTPAutoTLS = true; 설정

### ISSUE THREAD

**Issue by angelbro** [gnuboard/gnuboard5#61]
메일발송을 통해 아래와 같은 오류가 나오는 경우가 있습니다.
`Warning: stream_socket_enable_crypto(): Peer certificate CN=`server_name.domain.com' did not match expected CN=`127.0.0.1' in /path/public_html/www/plugin/PHPMailer/class.smtp.php on line 368`

위와 같은 현상이 발생시 
plugin/PHPMailer/class.phpmailer.php 260라인
`public $SMTPAutoTLS = true;`
를 false로 변경하면 정상적으로 작동하더군요.

이 부분을 범용으로 변경하여 사용하는 것이 좋은 방법인지 몰라 이슈로 제안드립니다.

**Comment by kagla** [comment]
답변이 늦었습니다.

정확하게 어떤 상황에 오류가 나오는지 알지 못해 우선 QA에서 문의하신 분들께 답변을 드렸습니다.

https://sir.kr/qa/?unanswered=&unadopted=&adopted=&sst=wr_num&s_tag=&stx=stream_socket_enable_crypto&sop=and
