### ISSUE TITLE
코드에 대한 문서는 따로 존재하지 않나요?

### ISSUE THREAD

**Issue by dbwodlf3** [gnuboard/gnuboard5#63]
코드에 대한 문서는 따로 존재하지 않나요?
소스코드와 주석만이 존재할까요?
레퍼런스가 있을까요?

공식페이지에서 메뉴얼이나 다른 자료들도 확인을 해 보았는데, 아키텍처나 코드구조 같은건 없고 그냥 사용방법만 나와있었습니다.
그냥 코드를 보면서 구조를 파악해야할까요?

**Comment by thisgun** [comment]
코드구조를 한곳에 모아둔 것은 없습니다.

구글에서 그누보드 구조 또는 그누보드 분석 이라고 검색하면 도움이 되는 자료가 나올겁니다.

**Comment by dbwodlf3** [comment]
Developer Guide 같은게 있으면 좋을 것 같습니다.
폴더구조와 파일만 나열해놓은 자료밖에 못찾겠습니다. 
중요한 정보들이 없는 것 같습니다. 
URL 라우팅은 어떻게 하는지. 
세션 관리는 어떻게 하는지. 
쿠키 관리는 어떻게 하는지. 
어떤 구조로 돌아가는지. 
등등..

코드에 대한 Developer Guide 나 Reference 같은걸 작성한다면 무척이나 도움이 될 것 같습니다.

**Comment by dbwodlf3** [comment]
Readme.md 파일도 작성하면 좋을 것 같습니다.

**Comment by dbwodlf3** [comment]
버전관리 브랜치도 만들면 좋을 것 같습니다.

**Comment by thisgun** [comment]
세션관리와 쿠키관리는 PHP 기본구조를 따릅니다.

PHP 페이지를 직접 호출하기 때문에, URL 라우팅이 없습니다.

**Comment by dbwodlf3** [comment]
guide 문서를 작성해서 병합하고 싶습니다.
그런데 프로젝트 구조상 임의의 폴더를 마음대로 집어넣는 것은 상당히 곤란 해 보입니다.
프로젝트 구조를 조금 수정을 하는 것은 어떨까요?

gnuboard5/src/현재의 소스파일
gnuboard5/readme.md
gnuboard5/something....

이러한 폴더 구조를 수정하는 것이 곤란하고, 문서를 추가할 수 없다면 github의 위키를 이용할 수 있을까요?

**Comment by thisgun** [comment]
저희 SIR 홈페이지에도 미흡한 부분이 많아서... 다른곳에 신경을 분산할수는 없습니다.

**Comment by woosungchoi** [comment]
Wiki 정말 좋아요!

**Comment by devrainbow** [comment]
> 저희 SIR 홈페이지에도 미흡한 부분이 많아서... 다른곳에 신경을 분산할수는 없습니다.

그누보드는 SIR의 제품인데 제품에 신경쓰는게 분산하는건가요??
