### ISSUE TITLE
코딩스타일에 대해서.

### ISSUE THREAD

**Issue by dbwodlf3** [gnuboard/gnuboard5#64]
그누보드 코드를 보는데 많은 부분에서 조금 가독성이 떨어지는 것 같습니다.
PSR에 맞게끔 코드를 수정하는 것이 어떨까요?

https://www.php-fig.org/psr/psr-2/

**Comment by kagla** [comment]
답변이 늦었습니다.
PSR 에 맞게 코딩 스타일을 바꾸는 것이 가장 좋은 방법이긴하나 전체 코드가 변경되어야 하는 관계로 지금 적용하기에는 무리가 있습니다.
