### ISSUE TITLE
SQL query distortion bug

### ISSUE THREAD

**Issue by dael** [gnuboard/gnuboard5#8]
https://github.com/gnuboard/gnuboard5/blob/master/lib/common.lib.php#L1452
'''php
$sql = preg_replace("#^select._from._union.*#i", "select 1", $sql);
'''

사용자 입력 문자열에 union이라는 문자열이 포함 되어 있으면 return 하여 의도치 않은 동작 야기.

email, mb_id 등에 union을 못사용하는 문제점 발생.
SQL injection 방지를 위함이라면 mysql_real_escape_string 사용을 건의합니다.

**Comment by chicpro** [comment]
union 을 허용하지 않도록 한 것은 blind sql injection 때문입니다.
blind sql injection 은 mysql_real_escape_string 으로는 대처할 수가 없습니다.

**Comment by dael** [comment]
이미 DB 스키마가 공개되어있는 오픈소스 프로젝트인 그누보드에서 blind injection을 막는다는게 의미가 없어보입니다.
모든 사용자 입력 데이터들을 이스케이프 하는것이 맞겠지만 현재구조로서는 힘들어 보이므로
safety 데이터가 아닌 데이터들에 대해서만 처리하는게 좋지 않을까하는 의견입니다.
현재 방법으로는 정상적인 요청이 필터링되는 문제점이 있습니다.

**Comment by chicpro** [comment]
kisa의 요청에 의해 보안 패치된 부분입니다.
자료가 필터링되는 부분에 대해서는 인지하고 있지만 각자 수정하신 후 사용하시는 방법 밖에 없습니다.

**Comment by lansi951** [comment]
저도 지금 이 버그를 발견했네요
그누보드5의 sql_query 함수의
```$sql = preg_replace("#^select.*from.*[\s\(]+union[\s\)]+.*#i ", "select 1", $sql);```
```$sql = preg_replace("#^select.*from.*where.*`?information_schema`?.*#i", "select 1", $sql);```
이 부분을 복사해서 대체했더니 정상 작동합니다
정규식이 문제인 것 같습니다
그누5에서 사용하는 걸 그대로 사용한 것이니 4에서 변경이 됐으면 좋겠습니다
@dael @chicpro
