### ISSUE TITLE
kisa 취약점 제보 xss 필터 적용부분 문의

### ISSUE THREAD

**Issue by calintz100** [gnuboard/gnuboard5#83]
/bbs/write.php 238 line에 아래 코드가 있는데
html_purifier 함수를 왜 

" if ( $w == 'u' && (! $is_member || ! $is_admin || $write['mb_id'] !== $member['mb_id']) ) "

이조건에서만 실행 시키는건지 궁금합니다 해당 조건이면 비회원 수정시만 동작하게 되는건가요?

```
if ( $w == 'u' && (! $is_member || ! $is_admin || $write['mb_id'] !== $member['mb_id']) ){
// kisa 취약점 제보 xss 필터 적용
$content = get_text(html_purifier($write['wr_content']), 0);
}

```

**Comment by kagla** [comment]
답변이 늦었습니다.
구문상으로는 비회원 수정시에만 작동하도록 한것 같은데 코드 작성자가 없는 관계로 정확한 확인이 어렵습니다.
