### ISSUE TITLE
영카트 hook 추가 부탁드려도 될까요?

### ISSUE THREAD

**Issue by choiks14** [gnuboard/gnuboard5#87]
게시판 쪽의 훅은 많이 추가되어서 다양하게 활용하고 있습니다. 
근데 영카트 쪽이 조금 부족한듯 합니다. 

주문 등록,
관리자 주문 주문 변경등. 
추가 부탁 드립니다. 

항상 감사히 잘 사용하고 있습니다.

**Comment by kagla** [comment]
@choiks14 답변이 늦었습니다.
사용하시고자 하는 곳을 알려주시면 확인후 결정하겠습니다.
