### ISSUE TITLE
혹시 관리자 페이지에서 게시판 사용하는 계획이 있나요?

### ISSUE THREAD

**Issue by easylogic** [gnuboard/gnuboard5#9]
먼저 그누보드 만들어 주셔서 감사합니다. 

근래 사이트를 제작할 일이 있어서 그누보드를 처음부터 다시 설치해서 하는데. 

이걸 할 때마다 어드민 관련된 사이트를 다시 만들어야하나 고민이 많았습니다. 

일단 그누보드 관리자 페이지가 맘에 딱 드는 패턴이라 여기에 메뉴추가 하고 게시판 까지 있으면 좋겠다는 생각이 들었습니다. 

관리자 페이지에서 게시판 관리 이외에 실제 게시판 기능을 지원해주면 좋지 않을까 합니다. 

그러면  관리자 페이지를 위해서 사이트를 다시 재구성을 안해도 될 것 같아요. 

https://gist.github.com/easylogic/fc4e9ce2b60a8ab50ab9

그래서 한번 게시판을 써보자는 마음으로 했습니다.  일단 게시판 기능은 붙였는데요. 

너무 부자연스러운 것 같네요. 

기존 게시판 코어가 바뀔 때 마다 계속 수정하면서 써야해서 말이죠. 
별로 좋은 방법은 아닌 것 같습니다. 

좀 더 쉽게 구성할 수 있는 방법이 없을까요?

**Comment by chicpro** [comment]
배포판에서 관리자에 게시판 기능이 필요한 경우가 없기 때문에
관리자에 게시판을 추가할 계획은 없습니다.
